// apps/remote/src/app/board/board.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'tvp-board',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './board.component.html',
  styleUrls: ['./board.component.scss']
})
export class BoardComponent {
  date = new Date().toLocaleDateString();
}

<div>
  <h1>Welcome to the remote board</h1>
  <p>当前： {{ date }}</p>
</div>

// apps/remote-react/src/app/components/board.tsx
import React from 'react';
import style from './board.module.scss';

const Board: React.FC<{ data?: string }> = props => {
  const data = new Date().toLocaleDateString();
  return (
    <div className={style.board}>
      <h1>
        Welcome to the <span style={{ color: 'red' }}>react</span> board
      </h1>
      <p>当前： {data}</p>
      <p>传参： {props.data}</p>
    </div>
  );
};
export default Board;
